# Generated by Django 4.2.4 on 2023-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2500)),
                ('email', models.CharField(max_length=2500)),
                ('phone', models.CharField(max_length=10)),
                ('contact_person', models.CharField(max_length=2500)),
                ('contact_person_phone', models.CharField(max_length=10)),
                ('contact_person_email', models.CharField(max_length=2500)),
                ('speciality', models.JSONField()),
            ],
        ),
    ]
